# Generated by Django 2.1.4 on 2019-02-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elecric',
        ),
        migrations.AlterField(
            model_name='student',
            name='rem_hours',
            field=models.DateTimeField(),
        ),
    ]
