# Generated by Django 2.1.4 on 2019-02-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_auto_20190205_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rem_hours',
            field=models.IntegerField(),
        ),
    ]
