# Generated by Django 2.1.4 on 2019-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0003_auto_20190207_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_elec_usage',
            field=models.IntegerField(default=0),
        ),
    ]
