# Generated by Django 2.1.4 on 2019-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_student_total_elec_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rem_hours',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_elec_usage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
