# Generated by Django 2.1.4 on 2019-02-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_auto_20190207_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_inst',
            new_name='degree_prog',
        ),
    ]
