# Generated by Django 2.1.4 on 2019-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('dept_inst', models.CharField(max_length=30)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
    ]
