# Generated by Django 2.1.4 on 2019-02-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dept_inst',
            field=models.CharField(max_length=50),
        ),
    ]
