# Generated by Django 2.1.4 on 2019-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUReport', '0003_auto_20190207_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='depts_insts',
        ),
        migrations.AddField(
            model_name='report',
            name='dept_inst',
            field=models.CharField(default='jojo', max_length=50),
        ),
        migrations.DeleteModel(
            name='DeptInst',
        ),
    ]
