# Generated by Django 2.1.4 on 2019-02-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUReport', '0004_auto_20190207_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptInst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_inst', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='dept_inst',
        ),
        migrations.AddField(
            model_name='report',
            name='depts_insts',
            field=models.ManyToManyField(to='EUReport.DeptInst'),
        ),
    ]
