# Generated by Django 2.1.4 on 2019-02-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUReport', '0005_auto_20190207_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='deptinst',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000),
        ),
    ]
