# Generated by Django 2.1.4 on 2019-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EUReport', '0006_auto_20190207_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesters', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='depts_insts',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='deptinst',
            name='sems',
            field=models.ManyToManyField(to='EUReport.Semester'),
        ),
    ]
