# Generated by Django 2.1.7 on 2019-04-04 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_no',
        ),
        migrations.AddField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
