# Generated by Django 2.1.7 on 2019-04-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0003_auto_20190404_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='Jane', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Doe', max_length=30),
        ),
    ]
