# Generated by Django 2.1.7 on 2019-04-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0005_auto_20190405_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_prog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pinkcard.DegreeProg'),
        ),
    ]
