# Generated by Django 2.1.7 on 2019-04-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0007_auto_20190405_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_librarian',
        ),
    ]
