# Generated by Django 2.1.7 on 2019-04-05 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0010_auto_20190405_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
