# Generated by Django 2.1.7 on 2019-04-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0011_auto_20190405_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(null=True),
        ),
    ]
