# Generated by Django 2.1.7 on 2019-04-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0012_auto_20190405_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(default=1010),
            preserve_default=False,
        ),
    ]
