# Generated by Django 2.0.1 on 2019-05-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinkcard', '0013_auto_20190405_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_no',
            field=models.IntegerField(null=True),
        ),
    ]
