# Generated by Django 2.1.4 on 2019-02-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeProg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg_name', models.CharField(default='Non Major', max_length=200)),
            ],
            options={
                'ordering': ('deg_name',),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
                ('degree_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewing.DegreeProg')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('student_no', models.IntegerField()),
                ('rem_hours', models.DecimalField(decimal_places=2, default=20.0, max_digits=1000)),
                ('total_elec_usage', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('degree_prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewing.DegreeProg')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewing.Student'),
        ),
    ]
