# Generated by Django 2.1.4 on 2019-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=models.CharField(max_length=30), max_length=30),
        ),
    ]
