# Generated by Django 2.1.4 on 2019-03-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0002_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='prtiqylqil', max_length=30),
        ),
    ]
