# Generated by Django 2.1.4 on 2019-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0004_auto_20190308_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='aitcockwsz', max_length=30),
        ),
    ]
