# Generated by Django 2.1.4 on 2019-03-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0005_auto_20190308_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default='vdqlwtsrml', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='vpkffdrscv', max_length=30),
        ),
    ]
