# Generated by Django 2.1.4 on 2019-03-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewing', '0006_auto_20190308_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password2',
        ),
        migrations.AddField(
            model_name='student',
            name='pword',
            field=models.CharField(default='krngmpfhiy', max_length=30),
        ),
    ]
